[workspace]
members = ["sqllogictest", "sqllogictest-bin", "examples/*", "tests"]

[workspace.package]
version = "0.11.1"
edition = "2021"
homepage = "https://github.com/risinglightdb/sqllogictest-rs"
keywords = ["sql", "database", "parser", "cli"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/risinglightdb/sqllogictest-rs"

[patch.crates-io]
tokio-postgres = { git = "https://github.com/risinglightdb/rust-postgres", rev = "205af89aafb8fec5e8a75599e0401d5797932f13" }
postgres-types = { git = "https://github.com/risinglightdb/rust-postgres", rev = "205af89aafb8fec5e8a75599e0401d5797932f13" }
